// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu6STuWUc19tseXl5GeYI_UL5poD7YTpg',
    appId: '1:652197099411:web:3856ac1cff77eb88d55a66',
    messagingSenderId: '652197099411',
    projectId: 'sitheer',
    authDomain: 'sitheer.firebaseapp.com',
    storageBucket: 'sitheer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr-wmMEruhji5h1wIipSoxKYSyaLI4BDU',
    appId: '1:652197099411:android:69a50efe782b6478d55a66',
    messagingSenderId: '652197099411',
    projectId: 'sitheer',
    storageBucket: 'sitheer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDir09-_mukdj9ImAd_C6a6l6pIsI0BjNM',
    appId: '1:652197099411:ios:b943a49df8c7ab43d55a66',
    messagingSenderId: '652197099411',
    projectId: 'sitheer',
    storageBucket: 'sitheer.firebasestorage.app',
    iosBundleId: 'com.example.sitheer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDir09-_mukdj9ImAd_C6a6l6pIsI0BjNM',
    appId: '1:652197099411:ios:b943a49df8c7ab43d55a66',
    messagingSenderId: '652197099411',
    projectId: 'sitheer',
    storageBucket: 'sitheer.firebasestorage.app',
    iosBundleId: 'com.example.sitheer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu6STuWUc19tseXl5GeYI_UL5poD7YTpg',
    appId: '1:652197099411:web:8a4a5526a47da451d55a66',
    messagingSenderId: '652197099411',
    projectId: 'sitheer',
    authDomain: 'sitheer.firebaseapp.com',
    storageBucket: 'sitheer.firebasestorage.app',
  );
}
